#!/bin/sh
#

apk add nginx redis

chmod +x /tmp/entrypoint

cp -av /tmp/entrypoint /sbin/
cp -av /tmp/nginx.conf /etc/nginx/http.d/default.conf

######

cd /var/www

if [ ! -d /var/www/api ]; then
    wget https://github.com/kuole-o/api/archive/refs/heads/main.tar.gz
    tar xvf main.tar.gz && mv api-main api-build
    rm -f main.tar.gz
fi

cd /var/www/api-build

[ -d node_modules ] || npm i
[ -d dist ] || npm run build

mv dist /var/www/api
cp -av package.json /var/www/api/package.json
cp -av node_modules /var/www/api/node_modules
cp -av .env.example /var/www/api/.env
cp -av public /var/www/api/public

mkdir -p /var/www/api/logs
rm -rf /var/www/api-build

######
#   前端构建单独部署，放到这里最终得要端口号才能访问，不方便

# cd /var/www

# if [ ! -d /var/www/front-build ]; then
#     wget https://github.com/kuole-o/dailyhot/archive/refs/heads/main.tar.gz
#     tar xvf main.tar.gz && mv dailyhot-main front-build
#     rm -f main.tar.gz
# fi

# cd /var/www/front-build

# sed -i "s|Copyright By|$(date +'%Y')|" src/components/Footer.vue
# sed -i 's|"author": "imsyy"|"author": "APP_COPYRIGHT"|' package.json
# sed -i 's|"github": "https://github.com/imsyy"|"github": "APP_COPYRIGHT_URL"|' package.json

# echo "VITE_GLOBAL_API=/api" >.env
# echo "VITE_ICP=APP_ICP" >>.env
# echo "VITE_DIR=/" >>.env

# [ -d node_modules ] || npm i
# [ -d dist ] || npm run build

# mv dist /var/www/front
# rm -rf /var/www/front-build

######

rm -rf /tmp/*
