#!/bin/sh
#

# 加载环境变量
. /etc/profile

export NODE_ENV=docker

# 应用内存过量使用设置
sysctl vm.overcommit_memory=1

# ENV_REPLACER="s|APP_ICP|$APP_ICP|g"
# ENV_REPLACER="$ENV_REPLACER; s|APP_COPYRIGHT_URL|$APP_COPYRIGHT_URL|g"
# ENV_REPLACER="$ENV_REPLACER; s|APP_COPYRIGHT|$APP_COPYRIGHT|g"

# sed -i "$ENV_REPLACER" /var/www/front/assets/*.js

redis-server --daemonize yes &
node /var/www/api/index.js &
nginx -g "daemon off;"
